# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.download_target_envelope import DownloadTargetEnvelope
from ..types.upload_target_envelope import UploadTargetEnvelope
from .raw_client import AsyncRawFilesClient, RawFilesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FilesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFilesClient
        """
        return self._raw_client

    def request_file_upload(
        self,
        *,
        channel_id: str,
        file_name: str,
        mime_type: str,
        size_bytes: float,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadTargetEnvelope:
        """
        Get a presigned URL to share a file in a channel. Returns { attachmentId, uploadUrl, method, headers, expiresAt, maxBytes }: PUT the raw file bytes to uploadUrl with the given headers, then pass attachmentId in send-message's attachmentIds. You must be a member of the channel.

        Parameters
        ----------
        channel_id : str
            The channel the file will be shared in.

        file_name : str
            Original file name (with extension).

        mime_type : str
            MIME type. Allowed: images, text/code, application/pdf, json, xml, yaml, zip, gzip.

        size_bytes : float
            File size in bytes. Rejected if it exceeds the workspace file-size limit.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadTargetEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.files.request_file_upload(
            channel_id="channelId",
            file_name="fileName",
            mime_type="mimeType",
            size_bytes=1.1,
        )
        """
        _response = self._raw_client.request_file_upload(
            channel_id=channel_id,
            file_name=file_name,
            mime_type=mime_type,
            size_bytes=size_bytes,
            request_options=request_options,
        )
        return _response.data

    def request_file_download(
        self, *, channel_id: str, attachment_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> DownloadTargetEnvelope:
        """
        Get a presigned URL to download a file shared in a channel. Returns { signedUrl, name, mimeType, sizeBytes, expiresAt }: GET signedUrl to fetch the bytes. You must be a member of the channel the file belongs to.

        Parameters
        ----------
        channel_id : str

        attachment_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DownloadTargetEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.files.request_file_download(
            channel_id="channelId",
            attachment_id="attachmentId",
        )
        """
        _response = self._raw_client.request_file_download(
            channel_id=channel_id, attachment_id=attachment_id, request_options=request_options
        )
        return _response.data


class AsyncFilesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFilesClient
        """
        return self._raw_client

    async def request_file_upload(
        self,
        *,
        channel_id: str,
        file_name: str,
        mime_type: str,
        size_bytes: float,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadTargetEnvelope:
        """
        Get a presigned URL to share a file in a channel. Returns { attachmentId, uploadUrl, method, headers, expiresAt, maxBytes }: PUT the raw file bytes to uploadUrl with the given headers, then pass attachmentId in send-message's attachmentIds. You must be a member of the channel.

        Parameters
        ----------
        channel_id : str
            The channel the file will be shared in.

        file_name : str
            Original file name (with extension).

        mime_type : str
            MIME type. Allowed: images, text/code, application/pdf, json, xml, yaml, zip, gzip.

        size_bytes : float
            File size in bytes. Rejected if it exceeds the workspace file-size limit.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadTargetEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.files.request_file_upload(
                channel_id="channelId",
                file_name="fileName",
                mime_type="mimeType",
                size_bytes=1.1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.request_file_upload(
            channel_id=channel_id,
            file_name=file_name,
            mime_type=mime_type,
            size_bytes=size_bytes,
            request_options=request_options,
        )
        return _response.data

    async def request_file_download(
        self, *, channel_id: str, attachment_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> DownloadTargetEnvelope:
        """
        Get a presigned URL to download a file shared in a channel. Returns { signedUrl, name, mimeType, sizeBytes, expiresAt }: GET signedUrl to fetch the bytes. You must be a member of the channel the file belongs to.

        Parameters
        ----------
        channel_id : str

        attachment_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DownloadTargetEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.files.request_file_download(
                channel_id="channelId",
                attachment_id="attachmentId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.request_file_download(
            channel_id=channel_id, attachment_id=attachment_id, request_options=request_options
        )
        return _response.data
