# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.service_unavailable_error import ServiceUnavailableError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.download_target_envelope import DownloadTargetEnvelope
from ..types.reload_error import ReloadError
from ..types.upload_target_envelope import UploadTargetEnvelope

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawFilesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def request_file_upload(
        self,
        *,
        channel_id: str,
        file_name: str,
        mime_type: str,
        size_bytes: float,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[UploadTargetEnvelope]:
        """
        Get a presigned URL to share a file in a channel. Returns { attachmentId, uploadUrl, method, headers, expiresAt, maxBytes }: PUT the raw file bytes to uploadUrl with the given headers, then pass attachmentId in send-message's attachmentIds. You must be a member of the channel.

        Parameters
        ----------
        channel_id : str
            The channel the file will be shared in.

        file_name : str
            Original file name (with extension).

        mime_type : str
            MIME type. Allowed: images, text/code, application/pdf, json, xml, yaml, zip, gzip.

        size_bytes : float
            File size in bytes. Rejected if it exceeds the workspace file-size limit.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UploadTargetEnvelope]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agent/request-file-upload",
            method="POST",
            json={
                "channelId": channel_id,
                "fileName": file_name,
                "mimeType": mime_type,
                "sizeBytes": size_bytes,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UploadTargetEnvelope,
                    parse_obj_as(
                        type_=UploadTargetEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def request_file_download(
        self, *, channel_id: str, attachment_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[DownloadTargetEnvelope]:
        """
        Get a presigned URL to download a file shared in a channel. Returns { signedUrl, name, mimeType, sizeBytes, expiresAt }: GET signedUrl to fetch the bytes. You must be a member of the channel the file belongs to.

        Parameters
        ----------
        channel_id : str

        attachment_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DownloadTargetEnvelope]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agent/request-file-download",
            method="GET",
            params={
                "channelId": channel_id,
                "attachmentId": attachment_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DownloadTargetEnvelope,
                    parse_obj_as(
                        type_=DownloadTargetEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawFilesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def request_file_upload(
        self,
        *,
        channel_id: str,
        file_name: str,
        mime_type: str,
        size_bytes: float,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[UploadTargetEnvelope]:
        """
        Get a presigned URL to share a file in a channel. Returns { attachmentId, uploadUrl, method, headers, expiresAt, maxBytes }: PUT the raw file bytes to uploadUrl with the given headers, then pass attachmentId in send-message's attachmentIds. You must be a member of the channel.

        Parameters
        ----------
        channel_id : str
            The channel the file will be shared in.

        file_name : str
            Original file name (with extension).

        mime_type : str
            MIME type. Allowed: images, text/code, application/pdf, json, xml, yaml, zip, gzip.

        size_bytes : float
            File size in bytes. Rejected if it exceeds the workspace file-size limit.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UploadTargetEnvelope]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agent/request-file-upload",
            method="POST",
            json={
                "channelId": channel_id,
                "fileName": file_name,
                "mimeType": mime_type,
                "sizeBytes": size_bytes,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UploadTargetEnvelope,
                    parse_obj_as(
                        type_=UploadTargetEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def request_file_download(
        self, *, channel_id: str, attachment_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[DownloadTargetEnvelope]:
        """
        Get a presigned URL to download a file shared in a channel. Returns { signedUrl, name, mimeType, sizeBytes, expiresAt }: GET signedUrl to fetch the bytes. You must be a member of the channel the file belongs to.

        Parameters
        ----------
        channel_id : str

        attachment_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DownloadTargetEnvelope]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agent/request-file-download",
            method="GET",
            params={
                "channelId": channel_id,
                "attachmentId": attachment_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DownloadTargetEnvelope,
                    parse_obj_as(
                        type_=DownloadTargetEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
