# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.resolved_identity_envelope import ResolvedIdentityEnvelope
from ..types.verify_connection_envelope import VerifyConnectionEnvelope
from ..types.workspace_info_envelope import WorkspaceInfoEnvelope
from .raw_client import AsyncRawWorkspaceClient, RawWorkspaceClient


class WorkspaceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWorkspaceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWorkspaceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWorkspaceClient
        """
        return self._raw_client

    def resolve_identity(
        self,
        *,
        handle: typing.Optional[str] = None,
        email: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResolvedIdentityEnvelope:
        """
        Look up the identity id of a human or agent in this workspace by `@handle` or email. Use this when you need the `stated_by_identity_id` for `remember-memory` / `supersede-memory` and only have the person's handle or email on hand — avoids paging through `get-channel-members`. Pass exactly one of `handle` or `email`. Returns `{ id, kind: "user" | "agent", displayName, handle }`. Returns `not_found` for unknown handles/emails or accounts outside this workspace.

        Parameters
        ----------
        handle : typing.Optional[str]

        email : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResolvedIdentityEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.workspace.resolve_identity()
        """
        _response = self._raw_client.resolve_identity(handle=handle, email=email, request_options=request_options)
        return _response.data

    def whoami(self, *, request_options: typing.Optional[RequestOptions] = None) -> ResolvedIdentityEnvelope:
        """
        Return the authenticated caller's own identity, resolved from the API key — `{ id, kind: "user" | "agent", displayName, handle }`. Use this to get your OWN identity id (e.g. for `stated_by_identity_id` on `remember-memory` / `supersede-memory`, or the `identity_id` for `bootstrap-context`) without needing a handle or email. The counterpart to `resolve-identity`, which resolves OTHER members by `@handle`/email.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResolvedIdentityEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.workspace.whoami()
        """
        _response = self._raw_client.whoami(request_options=request_options)
        return _response.data

    def verify_connection(
        self, *, token: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VerifyConnectionEnvelope:
        """
        Confirm this agent is reachable from the Reload UI. Pass the token shown in the "Test connection" panel; the UI will flip to "Verified" once this call succeeds.

        Parameters
        ----------
        token : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VerifyConnectionEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.workspace.verify_connection(
            token="token",
        )
        """
        _response = self._raw_client.verify_connection(token=token, request_options=request_options)
        return _response.data

    def get_workspace_info(self, *, request_options: typing.Optional[RequestOptions] = None) -> WorkspaceInfoEnvelope:
        """
        Get workspace info including name, slug, member/channel/agent counts.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkspaceInfoEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.workspace.get_workspace_info()
        """
        _response = self._raw_client.get_workspace_info(request_options=request_options)
        return _response.data


class AsyncWorkspaceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWorkspaceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWorkspaceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWorkspaceClient
        """
        return self._raw_client

    async def resolve_identity(
        self,
        *,
        handle: typing.Optional[str] = None,
        email: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResolvedIdentityEnvelope:
        """
        Look up the identity id of a human or agent in this workspace by `@handle` or email. Use this when you need the `stated_by_identity_id` for `remember-memory` / `supersede-memory` and only have the person's handle or email on hand — avoids paging through `get-channel-members`. Pass exactly one of `handle` or `email`. Returns `{ id, kind: "user" | "agent", displayName, handle }`. Returns `not_found` for unknown handles/emails or accounts outside this workspace.

        Parameters
        ----------
        handle : typing.Optional[str]

        email : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResolvedIdentityEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workspace.resolve_identity()


        asyncio.run(main())
        """
        _response = await self._raw_client.resolve_identity(handle=handle, email=email, request_options=request_options)
        return _response.data

    async def whoami(self, *, request_options: typing.Optional[RequestOptions] = None) -> ResolvedIdentityEnvelope:
        """
        Return the authenticated caller's own identity, resolved from the API key — `{ id, kind: "user" | "agent", displayName, handle }`. Use this to get your OWN identity id (e.g. for `stated_by_identity_id` on `remember-memory` / `supersede-memory`, or the `identity_id` for `bootstrap-context`) without needing a handle or email. The counterpart to `resolve-identity`, which resolves OTHER members by `@handle`/email.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResolvedIdentityEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workspace.whoami()


        asyncio.run(main())
        """
        _response = await self._raw_client.whoami(request_options=request_options)
        return _response.data

    async def verify_connection(
        self, *, token: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VerifyConnectionEnvelope:
        """
        Confirm this agent is reachable from the Reload UI. Pass the token shown in the "Test connection" panel; the UI will flip to "Verified" once this call succeeds.

        Parameters
        ----------
        token : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VerifyConnectionEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workspace.verify_connection(
                token="token",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.verify_connection(token=token, request_options=request_options)
        return _response.data

    async def get_workspace_info(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WorkspaceInfoEnvelope:
        """
        Get workspace info including name, slug, member/channel/agent counts.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkspaceInfoEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workspace.get_workspace_info()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_workspace_info(request_options=request_options)
        return _response.data
