# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.channel_list_envelope import ChannelListEnvelope
from ..types.channel_manifest_envelope import ChannelManifestEnvelope
from ..types.channel_members_envelope import ChannelMembersEnvelope
from .raw_client import AsyncRawChannelsClient, RawChannelsClient


class ChannelsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawChannelsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawChannelsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawChannelsClient
        """
        return self._raw_client

    def get_channels(self, *, request_options: typing.Optional[RequestOptions] = None) -> ChannelListEnvelope:
        """
        List channels the caller can read, with id, name, purpose, and type.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChannelListEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.channels.get_channels()
        """
        _response = self._raw_client.get_channels(request_options=request_options)
        return _response.data

    def get_channel_members(
        self,
        *,
        channel_id: str,
        limit: typing.Optional[float] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ChannelMembersEnvelope:
        """
        List members in a channel with names and handles. Use this to know who you can @mention.

        Parameters
        ----------
        channel_id : str

        limit : typing.Optional[float]

        after : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChannelMembersEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.channels.get_channel_members(
            channel_id="channelId",
        )
        """
        _response = self._raw_client.get_channel_members(
            channel_id=channel_id, limit=limit, after=after, request_options=request_options
        )
        return _response.data

    def get_channel_manifest(
        self, *, channel_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ChannelManifestEnvelope:
        """
        Get detailed channel manifest: name, purpose, members, and recent message count (last 24h).

        Parameters
        ----------
        channel_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChannelManifestEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.channels.get_channel_manifest(
            channel_id="channelId",
        )
        """
        _response = self._raw_client.get_channel_manifest(channel_id=channel_id, request_options=request_options)
        return _response.data


class AsyncChannelsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawChannelsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawChannelsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawChannelsClient
        """
        return self._raw_client

    async def get_channels(self, *, request_options: typing.Optional[RequestOptions] = None) -> ChannelListEnvelope:
        """
        List channels the caller can read, with id, name, purpose, and type.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChannelListEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.channels.get_channels()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_channels(request_options=request_options)
        return _response.data

    async def get_channel_members(
        self,
        *,
        channel_id: str,
        limit: typing.Optional[float] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ChannelMembersEnvelope:
        """
        List members in a channel with names and handles. Use this to know who you can @mention.

        Parameters
        ----------
        channel_id : str

        limit : typing.Optional[float]

        after : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChannelMembersEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.channels.get_channel_members(
                channel_id="channelId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_channel_members(
            channel_id=channel_id, limit=limit, after=after, request_options=request_options
        )
        return _response.data

    async def get_channel_manifest(
        self, *, channel_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ChannelManifestEnvelope:
        """
        Get detailed channel manifest: name, purpose, members, and recent message count (last 24h).

        Parameters
        ----------
        channel_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChannelManifestEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.channels.get_channel_manifest(
                channel_id="channelId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_channel_manifest(channel_id=channel_id, request_options=request_options)
        return _response.data
