# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.bootstrap_context_envelope import BootstrapContextEnvelope
from ..types.derived_from_ref import DerivedFromRef
from ..types.edge_output_envelope import EdgeOutputEnvelope
from ..types.edge_type import EdgeType
from ..types.link_to_type import LinkToType
from ..types.memory_kind import MemoryKind
from ..types.memory_output_envelope import MemoryOutputEnvelope
from ..types.recall_expansion import RecallExpansion
from ..types.recall_filters import RecallFilters
from ..types.recall_subgraph_envelope import RecallSubgraphEnvelope
from ..types.search_memories_envelope import SearchMemoriesEnvelope
from ..types.ttl_preset import TtlPreset
from .raw_client import AsyncRawMemoryClient, RawMemoryClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MemoryClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMemoryClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMemoryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMemoryClient
        """
        return self._raw_client

    def search_memories(
        self,
        *,
        kind: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        tags: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        from_: typing.Optional[str] = None,
        to: typing.Optional[str] = None,
        scope_id: typing.Optional[str] = None,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchMemoriesEnvelope:
        """
        Structured filter over the workspace context graph (Memory nodes). Filter by kind / status / tags / date range / scope. Pair with recall for semantic ANN. Bounded by scope-membership ACL.

        Parameters
        ----------
        kind : typing.Optional[str]

        status : typing.Optional[str]

        q : typing.Optional[str]

        tags : typing.Optional[typing.Union[str, typing.Sequence[str]]]

        from_ : typing.Optional[str]

        to : typing.Optional[str]

        scope_id : typing.Optional[str]

        cursor : typing.Optional[str]

        limit : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchMemoriesEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.memory.search_memories()
        """
        _response = self._raw_client.search_memories(
            kind=kind,
            status=status,
            q=q,
            tags=tags,
            from_=from_,
            to=to,
            scope_id=scope_id,
            cursor=cursor,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    def remember_memory(
        self,
        *,
        content: str,
        kind: MemoryKind,
        scope_id: str,
        derived_from: typing.Sequence[DerivedFromRef],
        confidence: typing.Optional[float] = OMIT,
        ttl_seconds: typing.Optional[int] = OMIT,
        ttl_preset: typing.Optional[TtlPreset] = OMIT,
        stated_by_identity_id: typing.Optional[str] = OMIT,
        where: typing.Optional[str] = OMIT,
        why: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemoryOutputEnvelope:
        """
        Author a Memory (decision / fact / preference) into a scope. Requires ≥1 `derived_from` provenance pointer — a memory without provenance is a hallucination with metadata.

        Parameters
        ----------
        content : str

        kind : MemoryKind

        scope_id : str

        derived_from : typing.Sequence[DerivedFromRef]

        confidence : typing.Optional[float]

        ttl_seconds : typing.Optional[int]
            Raw TTL. Provide this OR ttl_preset, not both.

        ttl_preset : typing.Optional[TtlPreset]

        stated_by_identity_id : typing.Optional[str]

        where : typing.Optional[str]
            5W "Where" — origin context the claim was made in.

        why : typing.Optional[str]
            5W "Why" — reason the claim was captured.

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Free-form JSON metadata. Capped at 4KB serialized (server rejects oversize).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryOutputEnvelope
            Success

        Examples
        --------
        from reload import DerivedFromRef, ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.memory.remember_memory(
            content="content",
            kind="decision",
            scope_id="scope_id",
            derived_from=[
                DerivedFromRef(
                    kind="message",
                    id="id",
                )
            ],
        )
        """
        _response = self._raw_client.remember_memory(
            content=content,
            kind=kind,
            scope_id=scope_id,
            derived_from=derived_from,
            confidence=confidence,
            ttl_seconds=ttl_seconds,
            ttl_preset=ttl_preset,
            stated_by_identity_id=stated_by_identity_id,
            where=where,
            why=why,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def supersede_memory(
        self,
        *,
        old_memory_id: str,
        expected_version: int,
        new_content: str,
        derived_from: typing.Sequence[DerivedFromRef],
        confidence: typing.Optional[float] = OMIT,
        ttl_seconds: typing.Optional[int] = OMIT,
        ttl_preset: typing.Optional[TtlPreset] = OMIT,
        stated_by_identity_id: typing.Optional[str] = OMIT,
        where: typing.Optional[str] = OMIT,
        why: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemoryOutputEnvelope:
        """
        Supersede an existing Memory with a new version. `expected_version` guards against concurrent writes — a mismatch returns 409 VERSION_CONFLICT.

        Parameters
        ----------
        old_memory_id : str

        expected_version : int
            Optimistic-lock guard. Mismatch → 409.

        new_content : str

        derived_from : typing.Sequence[DerivedFromRef]

        confidence : typing.Optional[float]

        ttl_seconds : typing.Optional[int]

        ttl_preset : typing.Optional[TtlPreset]

        stated_by_identity_id : typing.Optional[str]

        where : typing.Optional[str]

        why : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Free-form JSON metadata. Capped at 4KB serialized (server rejects oversize).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryOutputEnvelope
            Success

        Examples
        --------
        from reload import DerivedFromRef, ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.memory.supersede_memory(
            old_memory_id="old_memory_id",
            expected_version=1,
            new_content="new_content",
            derived_from=[
                DerivedFromRef(
                    kind="message",
                    id="id",
                )
            ],
        )
        """
        _response = self._raw_client.supersede_memory(
            old_memory_id=old_memory_id,
            expected_version=expected_version,
            new_content=new_content,
            derived_from=derived_from,
            confidence=confidence,
            ttl_seconds=ttl_seconds,
            ttl_preset=ttl_preset,
            stated_by_identity_id=stated_by_identity_id,
            where=where,
            why=why,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def invalidate_memory(
        self,
        *,
        memory_id: str,
        expected_version: int,
        reason: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemoryOutputEnvelope:
        """
        Mark a Memory invalidated with a reason. Optimistic-locked via `expected_version`. Reversible with revalidate-memory.

        Parameters
        ----------
        memory_id : str

        expected_version : int

        reason : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryOutputEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.memory.invalidate_memory(
            memory_id="memory_id",
            expected_version=1,
            reason="reason",
        )
        """
        _response = self._raw_client.invalidate_memory(
            memory_id=memory_id, expected_version=expected_version, reason=reason, request_options=request_options
        )
        return _response.data

    def revalidate_memory(
        self, *, memory_id: str, expected_version: int, request_options: typing.Optional[RequestOptions] = None
    ) -> MemoryOutputEnvelope:
        """
        Revert an invalidated Memory back to current. Optimistic-locked via `expected_version`.

        Parameters
        ----------
        memory_id : str

        expected_version : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryOutputEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.memory.revalidate_memory(
            memory_id="memory_id",
            expected_version=1,
        )
        """
        _response = self._raw_client.revalidate_memory(
            memory_id=memory_id, expected_version=expected_version, request_options=request_options
        )
        return _response.data

    def link_nodes(
        self,
        *,
        from_id: str,
        to_id: str,
        edge_type: EdgeType,
        to_type: typing.Optional[LinkToType] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EdgeOutputEnvelope:
        """
        Create a typed edge in the context graph. Pass `to_type` explicitly when linking to a non-Memory node, or the edge silently lands as Memory→Memory.

        Parameters
        ----------
        from_id : str

        to_id : str

        edge_type : EdgeType

        to_type : typing.Optional[LinkToType]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EdgeOutputEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.memory.link_nodes(
            from_id="from_id",
            to_id="to_id",
            edge_type="OWNS",
        )
        """
        _response = self._raw_client.link_nodes(
            from_id=from_id,
            to_id=to_id,
            edge_type=edge_type,
            to_type=to_type,
            properties=properties,
            request_options=request_options,
        )
        return _response.data

    def flag_contradiction(
        self, *, a_id: str, b_id: str, note: str, request_options: typing.Optional[RequestOptions] = None
    ) -> EdgeOutputEnvelope:
        """
        Record a CONTRADICTS edge between two Memories with an explanatory note.

        Parameters
        ----------
        a_id : str

        b_id : str

        note : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EdgeOutputEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.memory.flag_contradiction(
            a_id="a_id",
            b_id="b_id",
            note="note",
        )
        """
        _response = self._raw_client.flag_contradiction(
            a_id=a_id, b_id=b_id, note=note, request_options=request_options
        )
        return _response.data

    def recall(
        self,
        *,
        query: typing.Optional[str] = OMIT,
        seed_id: typing.Optional[str] = OMIT,
        depth: typing.Optional[int] = OMIT,
        scope_id: typing.Optional[str] = OMIT,
        expand: typing.Optional[typing.Sequence[RecallExpansion]] = OMIT,
        filters: typing.Optional[RecallFilters] = OMIT,
        metadata_filter: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RecallSubgraphEnvelope:
        """
        Retrieve a ranked subgraph. Provide exactly one of `query` (semantic ANN) or `seed_id` (BFS neighborhood walk). Returns flat hits, the edges linking them, ranking scores, and provenance messages.

        Parameters
        ----------
        query : typing.Optional[str]
            Semantic query. Provide exactly one of query or seed_id.

        seed_id : typing.Optional[str]
            Neighborhood-walk seed. Provide exactly one of query or seed_id.

        depth : typing.Optional[int]
            BFS walk depth (with seed_id).

        scope_id : typing.Optional[str]

        expand : typing.Optional[typing.Sequence[RecallExpansion]]

        filters : typing.Optional[RecallFilters]

        metadata_filter : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecallSubgraphEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.memory.recall()
        """
        _response = self._raw_client.recall(
            query=query,
            seed_id=seed_id,
            depth=depth,
            scope_id=scope_id,
            expand=expand,
            filters=filters,
            metadata_filter=metadata_filter,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    def bootstrap_context(
        self,
        *,
        agent_identity_id: str,
        scope_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BootstrapContextEnvelope:
        """
        Return the current decisions, active constraints, open questions, scope membership, and a recent-activity summary for an agent identity — the orientation payload an agent loads at the start of a session.

        Parameters
        ----------
        agent_identity_id : str

        scope_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BootstrapContextEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.memory.bootstrap_context(
            agent_identity_id="agent_identity_id",
        )
        """
        _response = self._raw_client.bootstrap_context(
            agent_identity_id=agent_identity_id, scope_id=scope_id, request_options=request_options
        )
        return _response.data


class AsyncMemoryClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMemoryClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMemoryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMemoryClient
        """
        return self._raw_client

    async def search_memories(
        self,
        *,
        kind: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        tags: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        from_: typing.Optional[str] = None,
        to: typing.Optional[str] = None,
        scope_id: typing.Optional[str] = None,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchMemoriesEnvelope:
        """
        Structured filter over the workspace context graph (Memory nodes). Filter by kind / status / tags / date range / scope. Pair with recall for semantic ANN. Bounded by scope-membership ACL.

        Parameters
        ----------
        kind : typing.Optional[str]

        status : typing.Optional[str]

        q : typing.Optional[str]

        tags : typing.Optional[typing.Union[str, typing.Sequence[str]]]

        from_ : typing.Optional[str]

        to : typing.Optional[str]

        scope_id : typing.Optional[str]

        cursor : typing.Optional[str]

        limit : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchMemoriesEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.memory.search_memories()


        asyncio.run(main())
        """
        _response = await self._raw_client.search_memories(
            kind=kind,
            status=status,
            q=q,
            tags=tags,
            from_=from_,
            to=to,
            scope_id=scope_id,
            cursor=cursor,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    async def remember_memory(
        self,
        *,
        content: str,
        kind: MemoryKind,
        scope_id: str,
        derived_from: typing.Sequence[DerivedFromRef],
        confidence: typing.Optional[float] = OMIT,
        ttl_seconds: typing.Optional[int] = OMIT,
        ttl_preset: typing.Optional[TtlPreset] = OMIT,
        stated_by_identity_id: typing.Optional[str] = OMIT,
        where: typing.Optional[str] = OMIT,
        why: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemoryOutputEnvelope:
        """
        Author a Memory (decision / fact / preference) into a scope. Requires ≥1 `derived_from` provenance pointer — a memory without provenance is a hallucination with metadata.

        Parameters
        ----------
        content : str

        kind : MemoryKind

        scope_id : str

        derived_from : typing.Sequence[DerivedFromRef]

        confidence : typing.Optional[float]

        ttl_seconds : typing.Optional[int]
            Raw TTL. Provide this OR ttl_preset, not both.

        ttl_preset : typing.Optional[TtlPreset]

        stated_by_identity_id : typing.Optional[str]

        where : typing.Optional[str]
            5W "Where" — origin context the claim was made in.

        why : typing.Optional[str]
            5W "Why" — reason the claim was captured.

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Free-form JSON metadata. Capped at 4KB serialized (server rejects oversize).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryOutputEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi, DerivedFromRef

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.memory.remember_memory(
                content="content",
                kind="decision",
                scope_id="scope_id",
                derived_from=[
                    DerivedFromRef(
                        kind="message",
                        id="id",
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remember_memory(
            content=content,
            kind=kind,
            scope_id=scope_id,
            derived_from=derived_from,
            confidence=confidence,
            ttl_seconds=ttl_seconds,
            ttl_preset=ttl_preset,
            stated_by_identity_id=stated_by_identity_id,
            where=where,
            why=why,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def supersede_memory(
        self,
        *,
        old_memory_id: str,
        expected_version: int,
        new_content: str,
        derived_from: typing.Sequence[DerivedFromRef],
        confidence: typing.Optional[float] = OMIT,
        ttl_seconds: typing.Optional[int] = OMIT,
        ttl_preset: typing.Optional[TtlPreset] = OMIT,
        stated_by_identity_id: typing.Optional[str] = OMIT,
        where: typing.Optional[str] = OMIT,
        why: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemoryOutputEnvelope:
        """
        Supersede an existing Memory with a new version. `expected_version` guards against concurrent writes — a mismatch returns 409 VERSION_CONFLICT.

        Parameters
        ----------
        old_memory_id : str

        expected_version : int
            Optimistic-lock guard. Mismatch → 409.

        new_content : str

        derived_from : typing.Sequence[DerivedFromRef]

        confidence : typing.Optional[float]

        ttl_seconds : typing.Optional[int]

        ttl_preset : typing.Optional[TtlPreset]

        stated_by_identity_id : typing.Optional[str]

        where : typing.Optional[str]

        why : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Free-form JSON metadata. Capped at 4KB serialized (server rejects oversize).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryOutputEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi, DerivedFromRef

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.memory.supersede_memory(
                old_memory_id="old_memory_id",
                expected_version=1,
                new_content="new_content",
                derived_from=[
                    DerivedFromRef(
                        kind="message",
                        id="id",
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.supersede_memory(
            old_memory_id=old_memory_id,
            expected_version=expected_version,
            new_content=new_content,
            derived_from=derived_from,
            confidence=confidence,
            ttl_seconds=ttl_seconds,
            ttl_preset=ttl_preset,
            stated_by_identity_id=stated_by_identity_id,
            where=where,
            why=why,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def invalidate_memory(
        self,
        *,
        memory_id: str,
        expected_version: int,
        reason: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MemoryOutputEnvelope:
        """
        Mark a Memory invalidated with a reason. Optimistic-locked via `expected_version`. Reversible with revalidate-memory.

        Parameters
        ----------
        memory_id : str

        expected_version : int

        reason : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryOutputEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.memory.invalidate_memory(
                memory_id="memory_id",
                expected_version=1,
                reason="reason",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.invalidate_memory(
            memory_id=memory_id, expected_version=expected_version, reason=reason, request_options=request_options
        )
        return _response.data

    async def revalidate_memory(
        self, *, memory_id: str, expected_version: int, request_options: typing.Optional[RequestOptions] = None
    ) -> MemoryOutputEnvelope:
        """
        Revert an invalidated Memory back to current. Optimistic-locked via `expected_version`.

        Parameters
        ----------
        memory_id : str

        expected_version : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemoryOutputEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.memory.revalidate_memory(
                memory_id="memory_id",
                expected_version=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revalidate_memory(
            memory_id=memory_id, expected_version=expected_version, request_options=request_options
        )
        return _response.data

    async def link_nodes(
        self,
        *,
        from_id: str,
        to_id: str,
        edge_type: EdgeType,
        to_type: typing.Optional[LinkToType] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EdgeOutputEnvelope:
        """
        Create a typed edge in the context graph. Pass `to_type` explicitly when linking to a non-Memory node, or the edge silently lands as Memory→Memory.

        Parameters
        ----------
        from_id : str

        to_id : str

        edge_type : EdgeType

        to_type : typing.Optional[LinkToType]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EdgeOutputEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.memory.link_nodes(
                from_id="from_id",
                to_id="to_id",
                edge_type="OWNS",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.link_nodes(
            from_id=from_id,
            to_id=to_id,
            edge_type=edge_type,
            to_type=to_type,
            properties=properties,
            request_options=request_options,
        )
        return _response.data

    async def flag_contradiction(
        self, *, a_id: str, b_id: str, note: str, request_options: typing.Optional[RequestOptions] = None
    ) -> EdgeOutputEnvelope:
        """
        Record a CONTRADICTS edge between two Memories with an explanatory note.

        Parameters
        ----------
        a_id : str

        b_id : str

        note : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EdgeOutputEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.memory.flag_contradiction(
                a_id="a_id",
                b_id="b_id",
                note="note",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.flag_contradiction(
            a_id=a_id, b_id=b_id, note=note, request_options=request_options
        )
        return _response.data

    async def recall(
        self,
        *,
        query: typing.Optional[str] = OMIT,
        seed_id: typing.Optional[str] = OMIT,
        depth: typing.Optional[int] = OMIT,
        scope_id: typing.Optional[str] = OMIT,
        expand: typing.Optional[typing.Sequence[RecallExpansion]] = OMIT,
        filters: typing.Optional[RecallFilters] = OMIT,
        metadata_filter: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RecallSubgraphEnvelope:
        """
        Retrieve a ranked subgraph. Provide exactly one of `query` (semantic ANN) or `seed_id` (BFS neighborhood walk). Returns flat hits, the edges linking them, ranking scores, and provenance messages.

        Parameters
        ----------
        query : typing.Optional[str]
            Semantic query. Provide exactly one of query or seed_id.

        seed_id : typing.Optional[str]
            Neighborhood-walk seed. Provide exactly one of query or seed_id.

        depth : typing.Optional[int]
            BFS walk depth (with seed_id).

        scope_id : typing.Optional[str]

        expand : typing.Optional[typing.Sequence[RecallExpansion]]

        filters : typing.Optional[RecallFilters]

        metadata_filter : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecallSubgraphEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.memory.recall()


        asyncio.run(main())
        """
        _response = await self._raw_client.recall(
            query=query,
            seed_id=seed_id,
            depth=depth,
            scope_id=scope_id,
            expand=expand,
            filters=filters,
            metadata_filter=metadata_filter,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    async def bootstrap_context(
        self,
        *,
        agent_identity_id: str,
        scope_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BootstrapContextEnvelope:
        """
        Return the current decisions, active constraints, open questions, scope membership, and a recent-activity summary for an agent identity — the orientation payload an agent loads at the start of a session.

        Parameters
        ----------
        agent_identity_id : str

        scope_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BootstrapContextEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.memory.bootstrap_context(
                agent_identity_id="agent_identity_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.bootstrap_context(
            agent_identity_id=agent_identity_id, scope_id=scope_id, request_options=request_options
        )
        return _response.data
