# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_task_request_priority import CreateTaskRequestPriority
    from .create_task_request_status import CreateTaskRequestStatus
    from .list_my_tasks_request_status import ListMyTasksRequestStatus
    from .list_tasks_request_priority import ListTasksRequestPriority
    from .list_tasks_request_status import ListTasksRequestStatus
    from .update_task_request_priority import UpdateTaskRequestPriority
    from .update_task_request_status import UpdateTaskRequestStatus
_dynamic_imports: typing.Dict[str, str] = {
    "CreateTaskRequestPriority": ".create_task_request_priority",
    "CreateTaskRequestStatus": ".create_task_request_status",
    "ListMyTasksRequestStatus": ".list_my_tasks_request_status",
    "ListTasksRequestPriority": ".list_tasks_request_priority",
    "ListTasksRequestStatus": ".list_tasks_request_status",
    "UpdateTaskRequestPriority": ".update_task_request_priority",
    "UpdateTaskRequestStatus": ".update_task_request_status",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateTaskRequestPriority",
    "CreateTaskRequestStatus",
    "ListMyTasksRequestStatus",
    "ListTasksRequestPriority",
    "ListTasksRequestStatus",
    "UpdateTaskRequestPriority",
    "UpdateTaskRequestStatus",
]
