# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .artifact_ref import ArtifactRef
    from .artifact_ref_envelope import ArtifactRefEnvelope
    from .bootstrap_context import BootstrapContext
    from .bootstrap_context_envelope import BootstrapContextEnvelope
    from .channel import Channel
    from .channel_list_envelope import ChannelListEnvelope
    from .channel_manifest import ChannelManifest
    from .channel_manifest_envelope import ChannelManifestEnvelope
    from .channel_manifest_member import ChannelManifestMember
    from .channel_member import ChannelMember, ChannelMember_Agent, ChannelMember_Human, ChannelMember_System
    from .channel_member_agent import ChannelMemberAgent
    from .channel_member_human import ChannelMemberHuman
    from .channel_member_system import ChannelMemberSystem
    from .channel_members_envelope import ChannelMembersEnvelope
    from .channel_members_page import ChannelMembersPage
    from .derived_from_kind import DerivedFromKind
    from .derived_from_ref import DerivedFromRef
    from .download_target import DownloadTarget
    from .download_target_envelope import DownloadTargetEnvelope
    from .edge_output import EdgeOutput
    from .edge_output_envelope import EdgeOutputEnvelope
    from .edge_type import EdgeType
    from .file_chunk import FileChunk
    from .file_chunk_encoding import FileChunkEncoding
    from .file_chunk_envelope import FileChunkEnvelope
    from .link_to_type import LinkToType
    from .memory_kind import MemoryKind
    from .memory_output import MemoryOutput
    from .memory_output_envelope import MemoryOutputEnvelope
    from .memory_status import MemoryStatus
    from .mention import Mention
    from .mention_summary import MentionSummary
    from .mention_type import MentionType
    from .message import Message
    from .message_attachment import MessageAttachment
    from .message_envelope import MessageEnvelope
    from .message_output import MessageOutput
    from .message_output_envelope import MessageOutputEnvelope
    from .message_reaction import MessageReaction
    from .message_search_hit import MessageSearchHit
    from .message_sender_type import MessageSenderType
    from .message_summary import MessageSummary
    from .messages_page import MessagesPage
    from .messages_page_envelope import MessagesPageEnvelope
    from .meta import Meta
    from .pagination_meta import PaginationMeta
    from .pagination_meta_history_cutoff import PaginationMetaHistoryCutoff
    from .recall_expansion import RecallExpansion
    from .recall_filters import RecallFilters
    from .recall_score import RecallScore
    from .recall_subgraph import RecallSubgraph
    from .recall_subgraph_envelope import RecallSubgraphEnvelope
    from .reload_error import ReloadError
    from .reload_error_error import ReloadErrorError
    from .resolved_identity import ResolvedIdentity
    from .resolved_identity_envelope import ResolvedIdentityEnvelope
    from .resolved_identity_kind import ResolvedIdentityKind
    from .scope_kind import ScopeKind
    from .scope_ref import ScopeRef
    from .search_memories_envelope import SearchMemoriesEnvelope
    from .search_memories_response import SearchMemoriesResponse
    from .search_messages_envelope import SearchMessagesEnvelope
    from .search_messages_response import SearchMessagesResponse
    from .share_file import ShareFile
    from .share_file_envelope import ShareFileEnvelope
    from .task import Task
    from .task_comment import TaskComment
    from .task_comment_envelope import TaskCommentEnvelope
    from .task_envelope import TaskEnvelope
    from .task_list_envelope import TaskListEnvelope
    from .task_priority import TaskPriority
    from .task_status import TaskStatus
    from .ttl_preset import TtlPreset
    from .unread_mentions_envelope import UnreadMentionsEnvelope
    from .unread_mentions_response import UnreadMentionsResponse
    from .upload_target import UploadTarget
    from .upload_target_envelope import UploadTargetEnvelope
    from .upload_target_method import UploadTargetMethod
    from .verify_connection_envelope import VerifyConnectionEnvelope
    from .verify_connection_result import VerifyConnectionResult
    from .workspace_info import WorkspaceInfo
    from .workspace_info_envelope import WorkspaceInfoEnvelope
_dynamic_imports: typing.Dict[str, str] = {
    "ArtifactRef": ".artifact_ref",
    "ArtifactRefEnvelope": ".artifact_ref_envelope",
    "BootstrapContext": ".bootstrap_context",
    "BootstrapContextEnvelope": ".bootstrap_context_envelope",
    "Channel": ".channel",
    "ChannelListEnvelope": ".channel_list_envelope",
    "ChannelManifest": ".channel_manifest",
    "ChannelManifestEnvelope": ".channel_manifest_envelope",
    "ChannelManifestMember": ".channel_manifest_member",
    "ChannelMember": ".channel_member",
    "ChannelMemberAgent": ".channel_member_agent",
    "ChannelMemberHuman": ".channel_member_human",
    "ChannelMemberSystem": ".channel_member_system",
    "ChannelMember_Agent": ".channel_member",
    "ChannelMember_Human": ".channel_member",
    "ChannelMember_System": ".channel_member",
    "ChannelMembersEnvelope": ".channel_members_envelope",
    "ChannelMembersPage": ".channel_members_page",
    "DerivedFromKind": ".derived_from_kind",
    "DerivedFromRef": ".derived_from_ref",
    "DownloadTarget": ".download_target",
    "DownloadTargetEnvelope": ".download_target_envelope",
    "EdgeOutput": ".edge_output",
    "EdgeOutputEnvelope": ".edge_output_envelope",
    "EdgeType": ".edge_type",
    "FileChunk": ".file_chunk",
    "FileChunkEncoding": ".file_chunk_encoding",
    "FileChunkEnvelope": ".file_chunk_envelope",
    "LinkToType": ".link_to_type",
    "MemoryKind": ".memory_kind",
    "MemoryOutput": ".memory_output",
    "MemoryOutputEnvelope": ".memory_output_envelope",
    "MemoryStatus": ".memory_status",
    "Mention": ".mention",
    "MentionSummary": ".mention_summary",
    "MentionType": ".mention_type",
    "Message": ".message",
    "MessageAttachment": ".message_attachment",
    "MessageEnvelope": ".message_envelope",
    "MessageOutput": ".message_output",
    "MessageOutputEnvelope": ".message_output_envelope",
    "MessageReaction": ".message_reaction",
    "MessageSearchHit": ".message_search_hit",
    "MessageSenderType": ".message_sender_type",
    "MessageSummary": ".message_summary",
    "MessagesPage": ".messages_page",
    "MessagesPageEnvelope": ".messages_page_envelope",
    "Meta": ".meta",
    "PaginationMeta": ".pagination_meta",
    "PaginationMetaHistoryCutoff": ".pagination_meta_history_cutoff",
    "RecallExpansion": ".recall_expansion",
    "RecallFilters": ".recall_filters",
    "RecallScore": ".recall_score",
    "RecallSubgraph": ".recall_subgraph",
    "RecallSubgraphEnvelope": ".recall_subgraph_envelope",
    "ReloadError": ".reload_error",
    "ReloadErrorError": ".reload_error_error",
    "ResolvedIdentity": ".resolved_identity",
    "ResolvedIdentityEnvelope": ".resolved_identity_envelope",
    "ResolvedIdentityKind": ".resolved_identity_kind",
    "ScopeKind": ".scope_kind",
    "ScopeRef": ".scope_ref",
    "SearchMemoriesEnvelope": ".search_memories_envelope",
    "SearchMemoriesResponse": ".search_memories_response",
    "SearchMessagesEnvelope": ".search_messages_envelope",
    "SearchMessagesResponse": ".search_messages_response",
    "ShareFile": ".share_file",
    "ShareFileEnvelope": ".share_file_envelope",
    "Task": ".task",
    "TaskComment": ".task_comment",
    "TaskCommentEnvelope": ".task_comment_envelope",
    "TaskEnvelope": ".task_envelope",
    "TaskListEnvelope": ".task_list_envelope",
    "TaskPriority": ".task_priority",
    "TaskStatus": ".task_status",
    "TtlPreset": ".ttl_preset",
    "UnreadMentionsEnvelope": ".unread_mentions_envelope",
    "UnreadMentionsResponse": ".unread_mentions_response",
    "UploadTarget": ".upload_target",
    "UploadTargetEnvelope": ".upload_target_envelope",
    "UploadTargetMethod": ".upload_target_method",
    "VerifyConnectionEnvelope": ".verify_connection_envelope",
    "VerifyConnectionResult": ".verify_connection_result",
    "WorkspaceInfo": ".workspace_info",
    "WorkspaceInfoEnvelope": ".workspace_info_envelope",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ArtifactRef",
    "ArtifactRefEnvelope",
    "BootstrapContext",
    "BootstrapContextEnvelope",
    "Channel",
    "ChannelListEnvelope",
    "ChannelManifest",
    "ChannelManifestEnvelope",
    "ChannelManifestMember",
    "ChannelMember",
    "ChannelMemberAgent",
    "ChannelMemberHuman",
    "ChannelMemberSystem",
    "ChannelMember_Agent",
    "ChannelMember_Human",
    "ChannelMember_System",
    "ChannelMembersEnvelope",
    "ChannelMembersPage",
    "DerivedFromKind",
    "DerivedFromRef",
    "DownloadTarget",
    "DownloadTargetEnvelope",
    "EdgeOutput",
    "EdgeOutputEnvelope",
    "EdgeType",
    "FileChunk",
    "FileChunkEncoding",
    "FileChunkEnvelope",
    "LinkToType",
    "MemoryKind",
    "MemoryOutput",
    "MemoryOutputEnvelope",
    "MemoryStatus",
    "Mention",
    "MentionSummary",
    "MentionType",
    "Message",
    "MessageAttachment",
    "MessageEnvelope",
    "MessageOutput",
    "MessageOutputEnvelope",
    "MessageReaction",
    "MessageSearchHit",
    "MessageSenderType",
    "MessageSummary",
    "MessagesPage",
    "MessagesPageEnvelope",
    "Meta",
    "PaginationMeta",
    "PaginationMetaHistoryCutoff",
    "RecallExpansion",
    "RecallFilters",
    "RecallScore",
    "RecallSubgraph",
    "RecallSubgraphEnvelope",
    "ReloadError",
    "ReloadErrorError",
    "ResolvedIdentity",
    "ResolvedIdentityEnvelope",
    "ResolvedIdentityKind",
    "ScopeKind",
    "ScopeRef",
    "SearchMemoriesEnvelope",
    "SearchMemoriesResponse",
    "SearchMessagesEnvelope",
    "SearchMessagesResponse",
    "ShareFile",
    "ShareFileEnvelope",
    "Task",
    "TaskComment",
    "TaskCommentEnvelope",
    "TaskEnvelope",
    "TaskListEnvelope",
    "TaskPriority",
    "TaskStatus",
    "TtlPreset",
    "UnreadMentionsEnvelope",
    "UnreadMentionsResponse",
    "UploadTarget",
    "UploadTargetEnvelope",
    "UploadTargetMethod",
    "VerifyConnectionEnvelope",
    "VerifyConnectionResult",
    "WorkspaceInfo",
    "WorkspaceInfoEnvelope",
]
