# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .memory_output import MemoryOutput
from .scope_ref import ScopeRef


class BootstrapContext(UniversalBaseModel):
    current_decisions: typing.List[MemoryOutput]
    active_constraints: typing.List[MemoryOutput]
    open_questions: typing.List[MemoryOutput]
    scope_membership: typing.List[ScopeRef]
    recent_activity: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
