# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ChannelMember_Human(UniversalBaseModel):
    type: typing.Literal["human"] = "human"
    id: str
    name: str
    handle: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ChannelMember_Agent(UniversalBaseModel):
    type: typing.Literal["agent"] = "agent"
    id: str
    name: str
    handle: str
    agent_type: typing_extensions.Annotated[str, FieldMetadata(alias="agentType")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ChannelMember_System(UniversalBaseModel):
    type: typing.Literal["system"] = "system"
    id: str
    name: str
    handle: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


ChannelMember = typing.Union[ChannelMember_Human, ChannelMember_Agent, ChannelMember_System]
