# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .channel_manifest_member import ChannelManifestMember


class ChannelManifest(UniversalBaseModel):
    id: str
    name: str
    purpose: typing.Optional[str] = None
    type: str
    domain: typing.Optional[str] = None
    iris_enabled: typing_extensions.Annotated[bool, FieldMetadata(alias="irisEnabled")]
    members: typing.List[ChannelManifestMember]
    recent_message_count: typing_extensions.Annotated[int, FieldMetadata(alias="recentMessageCount")] = pydantic.Field()
    """
    Messages in the last 24h.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
