# This file was auto-generated by Fern from our API Definition.

import typing

EdgeType = typing.Union[
    typing.Literal[
        "OWNS",
        "OPERATED_BY",
        "MEMBER_OF",
        "IN_SCOPE",
        "IN_CHANNEL",
        "AUTHORED",
        "IN_THREAD",
        "MENTIONS",
        "DERIVED_FROM",
        "STATED_BY",
        "SUPERSEDES",
        "CONTRADICTS",
        "SUPPORTS",
        "REFERENCES",
        "CAN_READ",
        "CAN_WRITE",
    ],
    typing.Any,
]
