# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .edge_type import EdgeType


class EdgeOutput(UniversalBaseModel):
    id: str
    from_id: str
    from_type: str
    to_id: str
    to_type: str
    edge_type: EdgeType
    properties: typing.Dict[str, typing.Optional[typing.Any]]
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
