# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .file_chunk_encoding import FileChunkEncoding


class FileChunk(UniversalBaseModel):
    name: str
    mime_type: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="mimeType")] = None
    size_bytes: typing_extensions.Annotated[int, FieldMetadata(alias="sizeBytes")] = pydantic.Field()
    """
    Total file size in bytes.
    """

    offset: int = pydantic.Field()
    """
    Byte offset this chunk starts at.
    """

    bytes_returned: typing_extensions.Annotated[int, FieldMetadata(alias="bytesReturned")] = pydantic.Field()
    """
    Number of bytes in this chunk.
    """

    eof: bool = pydantic.Field()
    """
    True when this chunk reaches the end of the file.
    """

    next_offset: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="nextOffset")] = None
    encoding: FileChunkEncoding
    data: str = pydantic.Field()
    """
    Base64-encoded chunk bytes.
    """

    text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Decoded UTF-8 — present only for text MIME types.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
