# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .memory_kind import MemoryKind
from .memory_status import MemoryStatus


class MemoryOutput(UniversalBaseModel):
    id: str
    org_id: str
    kind: MemoryKind
    status: MemoryStatus
    content: str
    confidence: float = pydantic.Field()
    """
    0–1.
    """

    version: int
    ttl_seconds: typing.Optional[int] = None
    created_at: dt.datetime
    last_reinforced_at: dt.datetime
    expires_at: typing.Optional[dt.datetime] = None
    invalidated_at: typing.Optional[dt.datetime] = None
    invalidated_by: typing.Optional[str] = None
    invalidated_reason: typing.Optional[str] = None
    content_hash: str
    metadata: typing.Dict[str, typing.Optional[typing.Any]]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
