# This file was auto-generated by Fern from our API Definition.

import typing

MemoryStatus = typing.Union[
    typing.Literal["current", "proposed", "superseded", "contested", "expired", "invalidated"], typing.Any
]
