# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class MentionSummary(UniversalBaseModel):
    id: str
    channel_id: typing_extensions.Annotated[str, FieldMetadata(alias="channelId")]
    channel_name: typing_extensions.Annotated[str, FieldMetadata(alias="channelName")]
    parent_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="parentId")] = None
    sender_type: typing_extensions.Annotated[str, FieldMetadata(alias="senderType")]
    sender_id: typing_extensions.Annotated[str, FieldMetadata(alias="senderId")]
    content: str
    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
