# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class MessageAttachment(UniversalBaseModel):
    id: str
    message_id: typing_extensions.Annotated[str, FieldMetadata(alias="messageId")]
    name: str
    file_type: typing_extensions.Annotated[str, FieldMetadata(alias="fileType")] = pydantic.Field()
    """
    pdf | markdown | code | image
    """

    size: str = pydantic.Field()
    """
    Human-readable size, e.g. "2.4 KB".
    """

    size_bytes: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="sizeBytes")] = None
    url: typing.Optional[str] = None
    mime_type: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="mimeType")] = None
    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
