# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .message_attachment import MessageAttachment
from .message_reaction import MessageReaction
from .message_sender_type import MessageSenderType


class Message(UniversalBaseModel):
    id: str
    channel_id: typing_extensions.Annotated[str, FieldMetadata(alias="channelId")]
    parent_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="parentId")] = pydantic.Field(
        default=None
    )
    """
    Thread parent message id.
    """

    sender_type: typing_extensions.Annotated[MessageSenderType, FieldMetadata(alias="senderType")]
    sender_id: typing_extensions.Annotated[str, FieldMetadata(alias="senderId")]
    content: str
    metadata: typing.Dict[str, typing.Optional[typing.Any]]
    is_edited: typing_extensions.Annotated[bool, FieldMetadata(alias="isEdited")]
    version: int
    reply_count: typing_extensions.Annotated[int, FieldMetadata(alias="replyCount")]
    reactions: typing.List[MessageReaction]
    attachments: typing.List[MessageAttachment]
    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")]
    updated_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="updatedAt")]
    deleted_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="deletedAt")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
