# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .memory_kind import MemoryKind


class RecallFilters(UniversalBaseModel):
    kind: typing.Optional[MemoryKind] = None
    include_superseded: typing.Optional[bool] = None
    include_invalidated: typing.Optional[bool] = None
    include_expired: typing.Optional[bool] = None
    min_confidence: typing.Optional[float] = None
    min_similarity: typing.Optional[float] = pydantic.Field(default=None)
    """
    Cosine-similarity floor in [0,1].
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
