# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .edge_output import EdgeOutput
from .memory_output import MemoryOutput
from .message_output import MessageOutput
from .recall_score import RecallScore


class RecallSubgraph(UniversalBaseModel):
    hits: typing.List[MemoryOutput]
    edges: typing.List[EdgeOutput]
    scores: typing.List[RecallScore]
    messages: typing.Optional[typing.List[MessageOutput]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
