# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ReloadErrorError(UniversalBaseModel):
    code: str = pydantic.Field()
    """
    `/v1/agent/*` returns lowercase coarse codes (permission_denied, channel_not_member, not_found, invalid_input, conflict, rate_limited, upstream_unavailable, internal_error). `/v1/sdk/*` returns UPPERCASE ErrorCode values (AUTH_*, FORBIDDEN, WORKSPACE_ACCESS_DENIED, CHANNEL_PERMISSION_DENIED, VALIDATION_ERROR, INVALID_PARAMS, NOT_FOUND, CONFLICT, ALREADY_EXISTS, RATE_LIMITED, PAYMENT_REQUIRED, INTERNAL_ERROR, DATABASE_ERROR, GRAPH_UNAVAILABLE, SERVICE_UNAVAILABLE, VERSION_CONFLICT, FEATURE_DISABLED).
    """

    message: str
    details: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    retryable: typing.Optional[bool] = pydantic.Field(default=None)
    """
    `/v1/agent/*` only — whether retrying with the same args may succeed.
    """

    suggestion: typing.Optional[str] = pydantic.Field(default=None)
    """
    `/v1/sdk/*` only — a human-actionable hint.
    """

    docs: typing.Optional[str] = pydantic.Field(default=None)
    """
    `/v1/sdk/*` only — a documentation URL.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
