# This file was auto-generated by Fern from our API Definition.

import typing

TaskStatus = typing.Union[
    typing.Literal["triage", "backlog", "todo", "in_progress", "blocked", "in_review", "done", "cancelled"], typing.Any
]
