# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .mention import Mention


class TaskComment(UniversalBaseModel):
    id: str
    task_id: typing_extensions.Annotated[str, FieldMetadata(alias="taskId")]
    author_user_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="authorUserId")] = None
    author_agent_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="authorAgentId")] = None
    body: str
    parent_comment_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="parentCommentId")] = None
    resolved_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="resolvedAt")] = None
    mentions: typing.List[Mention]
    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")]
    updated_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="updatedAt")]
    deleted_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="deletedAt")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
