# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .task_priority import TaskPriority
from .task_status import TaskStatus


class Task(UniversalBaseModel):
    id: str
    identifier: str = pydantic.Field()
    """
    Human-readable id, e.g. "T-123" (unique per workspace).
    """

    workspace_id: typing_extensions.Annotated[str, FieldMetadata(alias="workspaceId")]
    title: str
    description: typing.Optional[str] = None
    status: TaskStatus
    priority: TaskPriority
    version: int = pydantic.Field()
    """
    Optimistic-lock version. Send as `If-Match` on update; 409 on mismatch.
    """

    due_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="dueAt")] = None
    assignee_user_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="assigneeUserId")] = None
    assignee_agent_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="assigneeAgentId")] = None
    created_by_user_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="createdByUserId")] = None
    created_by_agent_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="createdByAgentId")] = (
        None
    )
    parent_task_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="parentTaskId")] = None
    channel_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="channelId")] = None
    origin_message_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="originMessageId")] = None
    origin_extraction_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="originExtractionId")
    ] = None
    started_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="startedAt")] = None
    completed_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="completedAt")] = None
    cancelled_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="cancelledAt")] = None
    archived_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="archivedAt")] = None
    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")]
    updated_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="updatedAt")]
    deleted_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="deletedAt")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
