# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .upload_target_method import UploadTargetMethod


class UploadTarget(UniversalBaseModel):
    attachment_id: typing_extensions.Annotated[str, FieldMetadata(alias="attachmentId")]
    upload_url: typing_extensions.Annotated[str, FieldMetadata(alias="uploadUrl")] = pydantic.Field()
    """
    Presigned GCS PUT URL.
    """

    method: UploadTargetMethod
    headers: typing.Dict[str, str] = pydantic.Field()
    """
    Headers the caller MUST send on the raw PUT.
    """

    expires_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="expiresAt")]
    max_bytes: typing_extensions.Annotated[int, FieldMetadata(alias="maxBytes")] = pydantic.Field()
    """
    Workspace max file size in bytes.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
