# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.service_unavailable_error import ServiceUnavailableError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.artifact_ref_envelope import ArtifactRefEnvelope
from ..types.message_envelope import MessageEnvelope
from ..types.message_output_envelope import MessageOutputEnvelope
from ..types.messages_page_envelope import MessagesPageEnvelope
from ..types.reload_error import ReloadError
from ..types.search_messages_envelope import SearchMessagesEnvelope
from ..types.unread_mentions_envelope import UnreadMentionsEnvelope

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawMessagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def send_message(
        self,
        *,
        channel_id: str,
        content: str,
        thread_id: typing.Optional[str] = OMIT,
        attachment_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[MessageEnvelope]:
        """
        Send a message to a channel. Agents must be a channel member.

        Parameters
        ----------
        channel_id : str
            The channel to send the message to.

        content : str
            The message content (markdown supported).

        thread_id : typing.Optional[str]
            Optional parent message ID to reply in a thread.

        attachment_ids : typing.Optional[typing.Sequence[str]]
            Optional attachment ids to attach to the message. Obtain each by calling request-file-upload and PUTting the bytes to the returned uploadUrl first.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MessageEnvelope]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agent/send-message",
            method="POST",
            json={
                "channelId": channel_id,
                "content": content,
                "threadId": thread_id,
                "attachmentIds": attachment_ids,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageEnvelope,
                    parse_obj_as(
                        type_=MessageEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_messages(
        self,
        *,
        channel_id: str,
        limit: typing.Optional[float] = None,
        before: typing.Optional[str] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[MessagesPageEnvelope]:
        """
        Get messages from a channel with cursor-based pagination (before/after).

        Parameters
        ----------
        channel_id : str

        limit : typing.Optional[float]

        before : typing.Optional[str]

        after : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MessagesPageEnvelope]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agent/get-messages",
            method="GET",
            params={
                "channelId": channel_id,
                "limit": limit,
                "before": before,
                "after": after,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessagesPageEnvelope,
                    parse_obj_as(
                        type_=MessagesPageEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def search_messages(
        self,
        *,
        query: str,
        channel_id: typing.Optional[str] = None,
        limit: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SearchMessagesEnvelope]:
        """
        Full-text search over messages. Optionally scoped to a channel.

        Parameters
        ----------
        query : str

        channel_id : typing.Optional[str]

        limit : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SearchMessagesEnvelope]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agent/search-messages",
            method="GET",
            params={
                "query": query,
                "channelId": channel_id,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchMessagesEnvelope,
                    parse_obj_as(
                        type_=SearchMessagesEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_unread_mentions(
        self,
        *,
        limit: typing.Optional[float] = None,
        since: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[UnreadMentionsEnvelope]:
        """
        Find messages you should respond to — either @mentions of your handle, or new replies in a thread you have already participated in (parent author or prior replier). Excludes messages you have already replied to. Call this at the start of every session to pick up pending work.

        Parameters
        ----------
        limit : typing.Optional[float]

        since : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UnreadMentionsEnvelope]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agent/get-unread-mentions",
            method="GET",
            params={
                "limit": limit,
                "since": since,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UnreadMentionsEnvelope,
                    parse_obj_as(
                        type_=UnreadMentionsEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_artifact(
        self,
        *,
        channel_id: str,
        name: str,
        type: str,
        content: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ArtifactRefEnvelope]:
        """
        Share an artifact (code, document, markdown, image link) in a channel as a message.

        Parameters
        ----------
        channel_id : str
            The channel to share the artifact in.

        name : str
            Filename or artifact name.

        type : str
            Artifact type: code, markdown, document, image.

        content : str
            The artifact content (text/code).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ArtifactRefEnvelope]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agent/create-artifact",
            method="POST",
            json={
                "channelId": channel_id,
                "name": name,
                "type": type,
                "content": content,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ArtifactRefEnvelope,
                    parse_obj_as(
                        type_=ArtifactRefEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def flag_needs_human(
        self, *, message_id: str, reason: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MessageEnvelope]:
        """
        Flag a message as needing human review. Sets needsHuman metadata.

        Parameters
        ----------
        message_id : str
            The message ID to flag.

        reason : str
            Why this message needs human review.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MessageEnvelope]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agent/flag-needs-human",
            method="POST",
            json={
                "messageId": message_id,
                "reason": reason,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageEnvelope,
                    parse_obj_as(
                        type_=MessageEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def post_message(
        self,
        *,
        channel_id: str,
        content: str,
        kind: typing.Optional[str] = OMIT,
        parent_message_id: typing.Optional[str] = OMIT,
        mention_identity_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        reference_artifact_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[MessageOutputEnvelope]:
        """
        Write a Message into a channel, optionally threaded under a parent and referencing artifacts. Returns the created message in SDK wire format (snake_case).

        Parameters
        ----------
        channel_id : str

        content : str

        kind : typing.Optional[str]
            Free-form kind tag.

        parent_message_id : typing.Optional[str]
            Thread parent — server resolves to thread_id.

        mention_identity_ids : typing.Optional[typing.Sequence[str]]

        reference_artifact_ids : typing.Optional[typing.Sequence[str]]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Free-form JSON metadata. Capped at 4KB serialized (server rejects oversize).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MessageOutputEnvelope]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/sdk/post",
            method="POST",
            json={
                "channel_id": channel_id,
                "content": content,
                "kind": kind,
                "parent_message_id": parent_message_id,
                "mention_identity_ids": mention_identity_ids,
                "reference_artifact_ids": reference_artifact_ids,
                "metadata": metadata,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageOutputEnvelope,
                    parse_obj_as(
                        type_=MessageOutputEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawMessagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def send_message(
        self,
        *,
        channel_id: str,
        content: str,
        thread_id: typing.Optional[str] = OMIT,
        attachment_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[MessageEnvelope]:
        """
        Send a message to a channel. Agents must be a channel member.

        Parameters
        ----------
        channel_id : str
            The channel to send the message to.

        content : str
            The message content (markdown supported).

        thread_id : typing.Optional[str]
            Optional parent message ID to reply in a thread.

        attachment_ids : typing.Optional[typing.Sequence[str]]
            Optional attachment ids to attach to the message. Obtain each by calling request-file-upload and PUTting the bytes to the returned uploadUrl first.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MessageEnvelope]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agent/send-message",
            method="POST",
            json={
                "channelId": channel_id,
                "content": content,
                "threadId": thread_id,
                "attachmentIds": attachment_ids,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageEnvelope,
                    parse_obj_as(
                        type_=MessageEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_messages(
        self,
        *,
        channel_id: str,
        limit: typing.Optional[float] = None,
        before: typing.Optional[str] = None,
        after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[MessagesPageEnvelope]:
        """
        Get messages from a channel with cursor-based pagination (before/after).

        Parameters
        ----------
        channel_id : str

        limit : typing.Optional[float]

        before : typing.Optional[str]

        after : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MessagesPageEnvelope]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agent/get-messages",
            method="GET",
            params={
                "channelId": channel_id,
                "limit": limit,
                "before": before,
                "after": after,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessagesPageEnvelope,
                    parse_obj_as(
                        type_=MessagesPageEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def search_messages(
        self,
        *,
        query: str,
        channel_id: typing.Optional[str] = None,
        limit: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SearchMessagesEnvelope]:
        """
        Full-text search over messages. Optionally scoped to a channel.

        Parameters
        ----------
        query : str

        channel_id : typing.Optional[str]

        limit : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SearchMessagesEnvelope]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agent/search-messages",
            method="GET",
            params={
                "query": query,
                "channelId": channel_id,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchMessagesEnvelope,
                    parse_obj_as(
                        type_=SearchMessagesEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_unread_mentions(
        self,
        *,
        limit: typing.Optional[float] = None,
        since: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[UnreadMentionsEnvelope]:
        """
        Find messages you should respond to — either @mentions of your handle, or new replies in a thread you have already participated in (parent author or prior replier). Excludes messages you have already replied to. Call this at the start of every session to pick up pending work.

        Parameters
        ----------
        limit : typing.Optional[float]

        since : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UnreadMentionsEnvelope]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agent/get-unread-mentions",
            method="GET",
            params={
                "limit": limit,
                "since": since,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UnreadMentionsEnvelope,
                    parse_obj_as(
                        type_=UnreadMentionsEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_artifact(
        self,
        *,
        channel_id: str,
        name: str,
        type: str,
        content: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ArtifactRefEnvelope]:
        """
        Share an artifact (code, document, markdown, image link) in a channel as a message.

        Parameters
        ----------
        channel_id : str
            The channel to share the artifact in.

        name : str
            Filename or artifact name.

        type : str
            Artifact type: code, markdown, document, image.

        content : str
            The artifact content (text/code).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ArtifactRefEnvelope]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agent/create-artifact",
            method="POST",
            json={
                "channelId": channel_id,
                "name": name,
                "type": type,
                "content": content,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ArtifactRefEnvelope,
                    parse_obj_as(
                        type_=ArtifactRefEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def flag_needs_human(
        self, *, message_id: str, reason: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MessageEnvelope]:
        """
        Flag a message as needing human review. Sets needsHuman metadata.

        Parameters
        ----------
        message_id : str
            The message ID to flag.

        reason : str
            Why this message needs human review.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MessageEnvelope]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agent/flag-needs-human",
            method="POST",
            json={
                "messageId": message_id,
                "reason": reason,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageEnvelope,
                    parse_obj_as(
                        type_=MessageEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def post_message(
        self,
        *,
        channel_id: str,
        content: str,
        kind: typing.Optional[str] = OMIT,
        parent_message_id: typing.Optional[str] = OMIT,
        mention_identity_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        reference_artifact_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[MessageOutputEnvelope]:
        """
        Write a Message into a channel, optionally threaded under a parent and referencing artifacts. Returns the created message in SDK wire format (snake_case).

        Parameters
        ----------
        channel_id : str

        content : str

        kind : typing.Optional[str]
            Free-form kind tag.

        parent_message_id : typing.Optional[str]
            Thread parent — server resolves to thread_id.

        mention_identity_ids : typing.Optional[typing.Sequence[str]]

        reference_artifact_ids : typing.Optional[typing.Sequence[str]]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Free-form JSON metadata. Capped at 4KB serialized (server rejects oversize).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MessageOutputEnvelope]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/sdk/post",
            method="POST",
            json={
                "channel_id": channel_id,
                "content": content,
                "kind": kind,
                "parent_message_id": parent_message_id,
                "mention_identity_ids": mention_identity_ids,
                "reference_artifact_ids": reference_artifact_ids,
                "metadata": metadata,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageOutputEnvelope,
                    parse_obj_as(
                        type_=MessageOutputEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ReloadError,
                        parse_obj_as(
                            type_=ReloadError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
