# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.task_comment_envelope import TaskCommentEnvelope
from ..types.task_envelope import TaskEnvelope
from ..types.task_list_envelope import TaskListEnvelope
from .raw_client import AsyncRawTasksClient, RawTasksClient
from .types.create_task_request_priority import CreateTaskRequestPriority
from .types.create_task_request_status import CreateTaskRequestStatus
from .types.list_my_tasks_request_status import ListMyTasksRequestStatus
from .types.list_tasks_request_priority import ListTasksRequestPriority
from .types.list_tasks_request_status import ListTasksRequestStatus
from .types.update_task_request_priority import UpdateTaskRequestPriority
from .types.update_task_request_status import UpdateTaskRequestStatus

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TasksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTasksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTasksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTasksClient
        """
        return self._raw_client

    def create_task(
        self,
        *,
        title: str,
        description: typing.Optional[str] = OMIT,
        status: typing.Optional[CreateTaskRequestStatus] = OMIT,
        priority: typing.Optional[CreateTaskRequestPriority] = OMIT,
        assignee_agent_id: typing.Optional[str] = OMIT,
        assignee_user_id: typing.Optional[str] = OMIT,
        parent_task_id: typing.Optional[str] = OMIT,
        channel_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskEnvelope:
        """
        Create a task in the workspace. Optionally assign to a user or agent, set priority, bind to a channel. Counts against the workspace plan's monthly task allowance — returns a plan_limit_reached error once the limit is hit until the next billing period or an upgrade.

        Parameters
        ----------
        title : str
            Short task title (1–500 chars).

        description : typing.Optional[str]
            Task description in markdown.

        status : typing.Optional[CreateTaskRequestStatus]
            Initial status.

        priority : typing.Optional[CreateTaskRequestPriority]
            Priority level.

        assignee_agent_id : typing.Optional[str]
            Agent ID to assign this task to.

        assignee_user_id : typing.Optional[str]
            User ID to assign this task to.

        parent_task_id : typing.Optional[str]
            Parent task ID for sub-task hierarchy.

        channel_id : typing.Optional[str]
            Channel ID to bind this task to (lifecycle events post TaskCard messages).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.tasks.create_task(
            title="title",
        )
        """
        _response = self._raw_client.create_task(
            title=title,
            description=description,
            status=status,
            priority=priority,
            assignee_agent_id=assignee_agent_id,
            assignee_user_id=assignee_user_id,
            parent_task_id=parent_task_id,
            channel_id=channel_id,
            request_options=request_options,
        )
        return _response.data

    def create_tasks_bulk(
        self,
        *,
        tasks: str,
        summary_channel_id: typing.Optional[str] = OMIT,
        summary_message: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskListEnvelope:
        """
        Create multiple tasks atomically (up to 50). Optionally post a summary message to a channel mentioning all assignees. The whole batch counts against the workspace plan's monthly task allowance — if it would exceed the remaining allowance the entire batch is rejected with a plan_limit_reached error.

        Parameters
        ----------
        tasks : str
            JSON array of task objects, each with: title (required), description?, status?, priority?, assigneeAgentId?, assigneeUserId?, parentTaskId?, channelId?. Max 50 tasks.

        summary_channel_id : typing.Optional[str]
            Channel ID to post a summary message to after creating all tasks.

        summary_message : typing.Optional[str]
            Summary message text to post in the channel (your narration of the breakdown).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskListEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.tasks.create_tasks_bulk(
            tasks="tasks",
        )
        """
        _response = self._raw_client.create_tasks_bulk(
            tasks=tasks,
            summary_channel_id=summary_channel_id,
            summary_message=summary_message,
            request_options=request_options,
        )
        return _response.data

    def update_task(
        self,
        *,
        task_id: str,
        version: float,
        status: typing.Optional[UpdateTaskRequestStatus] = OMIT,
        priority: typing.Optional[UpdateTaskRequestPriority] = OMIT,
        title: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        assignee_agent_id: typing.Optional[str] = OMIT,
        assignee_user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskEnvelope:
        """
        Update a task. Read-modify-write contract — read the task first to get its `version`, then call this with the same version. The server returns 409 if the task was changed in between; in that case re-read and retry. Supports status, priority, title, description, assignee, due date, and channel binding.

        Parameters
        ----------
        task_id : str
            The task ID to update.

        version : float
            Optimistic-lock version. Must match the task's current `version` field as returned by `list-tasks` / `list-my-tasks`. If the task was modified in between, the call returns 409 and you must re-read and retry.

        status : typing.Optional[UpdateTaskRequestStatus]
            New status.

        priority : typing.Optional[UpdateTaskRequestPriority]
            New priority.

        title : typing.Optional[str]
            Updated title.

        description : typing.Optional[str]
            Updated description (markdown).

        assignee_agent_id : typing.Optional[str]
            Agent ID to assign to (null to unassign).

        assignee_user_id : typing.Optional[str]
            User ID to assign to (null to unassign).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.tasks.update_task(
            task_id="taskId",
            version=1.1,
        )
        """
        _response = self._raw_client.update_task(
            task_id=task_id,
            version=version,
            status=status,
            priority=priority,
            title=title,
            description=description,
            assignee_agent_id=assignee_agent_id,
            assignee_user_id=assignee_user_id,
            request_options=request_options,
        )
        return _response.data

    def complete_task(self, *, task_id: str, request_options: typing.Optional[RequestOptions] = None) -> TaskEnvelope:
        """
        Mark a task as done. Equivalent to update-task with status=done.

        Parameters
        ----------
        task_id : str
            The task ID to complete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.tasks.complete_task(
            task_id="taskId",
        )
        """
        _response = self._raw_client.complete_task(task_id=task_id, request_options=request_options)
        return _response.data

    def cancel_task(
        self,
        *,
        task_id: str,
        reason: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskEnvelope:
        """
        Cancel a task. Adds a comment with the cancellation reason.

        Parameters
        ----------
        task_id : str
            The task ID to cancel.

        reason : typing.Optional[str]
            Why this task is being cancelled (posted as a comment).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.tasks.cancel_task(
            task_id="taskId",
        )
        """
        _response = self._raw_client.cancel_task(task_id=task_id, reason=reason, request_options=request_options)
        return _response.data

    def block_task(
        self, *, task_id: str, reason: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TaskEnvelope:
        """
        Mark a task as blocked. Automatically adds a comment with the blocking reason.

        Parameters
        ----------
        task_id : str
            The task ID to block.

        reason : str
            Why this task is blocked (posted as a comment).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.tasks.block_task(
            task_id="taskId",
            reason="reason",
        )
        """
        _response = self._raw_client.block_task(task_id=task_id, reason=reason, request_options=request_options)
        return _response.data

    def release_task(self, *, task_id: str, request_options: typing.Optional[RequestOptions] = None) -> TaskEnvelope:
        """
        Release a task you are currently assigned to. Clears your assignment so another agent or user can claim it.

        Parameters
        ----------
        task_id : str
            The task ID to release.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.tasks.release_task(
            task_id="taskId",
        )
        """
        _response = self._raw_client.release_task(task_id=task_id, request_options=request_options)
        return _response.data

    def list_tasks(
        self,
        *,
        status: typing.Optional[ListTasksRequestStatus] = None,
        assignee_agent_id: typing.Optional[str] = None,
        assignee_user_id: typing.Optional[str] = None,
        priority: typing.Optional[ListTasksRequestPriority] = None,
        channel_id: typing.Optional[str] = None,
        query: typing.Optional[str] = None,
        limit: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskListEnvelope:
        """
        List tasks visible to you — tasks you (or an agent you own) are assigned to, created, commented on, or are @mentioned in, plus tasks in channels you belong to. Supports filtering by status, assignee, priority, channel, and text search. You will not see tasks you are not a participant in.

        Parameters
        ----------
        status : typing.Optional[ListTasksRequestStatus]

        assignee_agent_id : typing.Optional[str]

        assignee_user_id : typing.Optional[str]

        priority : typing.Optional[ListTasksRequestPriority]

        channel_id : typing.Optional[str]

        query : typing.Optional[str]

        limit : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskListEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.tasks.list_tasks()
        """
        _response = self._raw_client.list_tasks(
            status=status,
            assignee_agent_id=assignee_agent_id,
            assignee_user_id=assignee_user_id,
            priority=priority,
            channel_id=channel_id,
            query=query,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    def list_my_tasks(
        self,
        *,
        status: typing.Optional[ListMyTasksRequestStatus] = None,
        limit: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskListEnvelope:
        """
        List tasks assigned to you. Filter by status to see only open/done/blocked tasks.

        Parameters
        ----------
        status : typing.Optional[ListMyTasksRequestStatus]

        limit : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskListEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.tasks.list_my_tasks()
        """
        _response = self._raw_client.list_my_tasks(status=status, limit=limit, request_options=request_options)
        return _response.data

    def comment_on_task(
        self, *, task_id: str, body: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TaskCommentEnvelope:
        """
        Add a comment to a task. Supports @mentions in the mentions array.

        Parameters
        ----------
        task_id : str
            The task ID to comment on.

        body : str
            Comment body (markdown).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskCommentEnvelope
            Success

        Examples
        --------
        from reload import ReloadApi

        client = ReloadApi(
            token="YOUR_TOKEN",
        )
        client.tasks.comment_on_task(
            task_id="taskId",
            body="body",
        )
        """
        _response = self._raw_client.comment_on_task(task_id=task_id, body=body, request_options=request_options)
        return _response.data


class AsyncTasksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTasksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTasksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTasksClient
        """
        return self._raw_client

    async def create_task(
        self,
        *,
        title: str,
        description: typing.Optional[str] = OMIT,
        status: typing.Optional[CreateTaskRequestStatus] = OMIT,
        priority: typing.Optional[CreateTaskRequestPriority] = OMIT,
        assignee_agent_id: typing.Optional[str] = OMIT,
        assignee_user_id: typing.Optional[str] = OMIT,
        parent_task_id: typing.Optional[str] = OMIT,
        channel_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskEnvelope:
        """
        Create a task in the workspace. Optionally assign to a user or agent, set priority, bind to a channel. Counts against the workspace plan's monthly task allowance — returns a plan_limit_reached error once the limit is hit until the next billing period or an upgrade.

        Parameters
        ----------
        title : str
            Short task title (1–500 chars).

        description : typing.Optional[str]
            Task description in markdown.

        status : typing.Optional[CreateTaskRequestStatus]
            Initial status.

        priority : typing.Optional[CreateTaskRequestPriority]
            Priority level.

        assignee_agent_id : typing.Optional[str]
            Agent ID to assign this task to.

        assignee_user_id : typing.Optional[str]
            User ID to assign this task to.

        parent_task_id : typing.Optional[str]
            Parent task ID for sub-task hierarchy.

        channel_id : typing.Optional[str]
            Channel ID to bind this task to (lifecycle events post TaskCard messages).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.create_task(
                title="title",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_task(
            title=title,
            description=description,
            status=status,
            priority=priority,
            assignee_agent_id=assignee_agent_id,
            assignee_user_id=assignee_user_id,
            parent_task_id=parent_task_id,
            channel_id=channel_id,
            request_options=request_options,
        )
        return _response.data

    async def create_tasks_bulk(
        self,
        *,
        tasks: str,
        summary_channel_id: typing.Optional[str] = OMIT,
        summary_message: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskListEnvelope:
        """
        Create multiple tasks atomically (up to 50). Optionally post a summary message to a channel mentioning all assignees. The whole batch counts against the workspace plan's monthly task allowance — if it would exceed the remaining allowance the entire batch is rejected with a plan_limit_reached error.

        Parameters
        ----------
        tasks : str
            JSON array of task objects, each with: title (required), description?, status?, priority?, assigneeAgentId?, assigneeUserId?, parentTaskId?, channelId?. Max 50 tasks.

        summary_channel_id : typing.Optional[str]
            Channel ID to post a summary message to after creating all tasks.

        summary_message : typing.Optional[str]
            Summary message text to post in the channel (your narration of the breakdown).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskListEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.create_tasks_bulk(
                tasks="tasks",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_tasks_bulk(
            tasks=tasks,
            summary_channel_id=summary_channel_id,
            summary_message=summary_message,
            request_options=request_options,
        )
        return _response.data

    async def update_task(
        self,
        *,
        task_id: str,
        version: float,
        status: typing.Optional[UpdateTaskRequestStatus] = OMIT,
        priority: typing.Optional[UpdateTaskRequestPriority] = OMIT,
        title: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        assignee_agent_id: typing.Optional[str] = OMIT,
        assignee_user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskEnvelope:
        """
        Update a task. Read-modify-write contract — read the task first to get its `version`, then call this with the same version. The server returns 409 if the task was changed in between; in that case re-read and retry. Supports status, priority, title, description, assignee, due date, and channel binding.

        Parameters
        ----------
        task_id : str
            The task ID to update.

        version : float
            Optimistic-lock version. Must match the task's current `version` field as returned by `list-tasks` / `list-my-tasks`. If the task was modified in between, the call returns 409 and you must re-read and retry.

        status : typing.Optional[UpdateTaskRequestStatus]
            New status.

        priority : typing.Optional[UpdateTaskRequestPriority]
            New priority.

        title : typing.Optional[str]
            Updated title.

        description : typing.Optional[str]
            Updated description (markdown).

        assignee_agent_id : typing.Optional[str]
            Agent ID to assign to (null to unassign).

        assignee_user_id : typing.Optional[str]
            User ID to assign to (null to unassign).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.update_task(
                task_id="taskId",
                version=1.1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_task(
            task_id=task_id,
            version=version,
            status=status,
            priority=priority,
            title=title,
            description=description,
            assignee_agent_id=assignee_agent_id,
            assignee_user_id=assignee_user_id,
            request_options=request_options,
        )
        return _response.data

    async def complete_task(
        self, *, task_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TaskEnvelope:
        """
        Mark a task as done. Equivalent to update-task with status=done.

        Parameters
        ----------
        task_id : str
            The task ID to complete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.complete_task(
                task_id="taskId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.complete_task(task_id=task_id, request_options=request_options)
        return _response.data

    async def cancel_task(
        self,
        *,
        task_id: str,
        reason: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskEnvelope:
        """
        Cancel a task. Adds a comment with the cancellation reason.

        Parameters
        ----------
        task_id : str
            The task ID to cancel.

        reason : typing.Optional[str]
            Why this task is being cancelled (posted as a comment).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.cancel_task(
                task_id="taskId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_task(task_id=task_id, reason=reason, request_options=request_options)
        return _response.data

    async def block_task(
        self, *, task_id: str, reason: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TaskEnvelope:
        """
        Mark a task as blocked. Automatically adds a comment with the blocking reason.

        Parameters
        ----------
        task_id : str
            The task ID to block.

        reason : str
            Why this task is blocked (posted as a comment).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.block_task(
                task_id="taskId",
                reason="reason",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.block_task(task_id=task_id, reason=reason, request_options=request_options)
        return _response.data

    async def release_task(
        self, *, task_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TaskEnvelope:
        """
        Release a task you are currently assigned to. Clears your assignment so another agent or user can claim it.

        Parameters
        ----------
        task_id : str
            The task ID to release.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.release_task(
                task_id="taskId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.release_task(task_id=task_id, request_options=request_options)
        return _response.data

    async def list_tasks(
        self,
        *,
        status: typing.Optional[ListTasksRequestStatus] = None,
        assignee_agent_id: typing.Optional[str] = None,
        assignee_user_id: typing.Optional[str] = None,
        priority: typing.Optional[ListTasksRequestPriority] = None,
        channel_id: typing.Optional[str] = None,
        query: typing.Optional[str] = None,
        limit: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskListEnvelope:
        """
        List tasks visible to you — tasks you (or an agent you own) are assigned to, created, commented on, or are @mentioned in, plus tasks in channels you belong to. Supports filtering by status, assignee, priority, channel, and text search. You will not see tasks you are not a participant in.

        Parameters
        ----------
        status : typing.Optional[ListTasksRequestStatus]

        assignee_agent_id : typing.Optional[str]

        assignee_user_id : typing.Optional[str]

        priority : typing.Optional[ListTasksRequestPriority]

        channel_id : typing.Optional[str]

        query : typing.Optional[str]

        limit : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskListEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.list_tasks()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_tasks(
            status=status,
            assignee_agent_id=assignee_agent_id,
            assignee_user_id=assignee_user_id,
            priority=priority,
            channel_id=channel_id,
            query=query,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    async def list_my_tasks(
        self,
        *,
        status: typing.Optional[ListMyTasksRequestStatus] = None,
        limit: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskListEnvelope:
        """
        List tasks assigned to you. Filter by status to see only open/done/blocked tasks.

        Parameters
        ----------
        status : typing.Optional[ListMyTasksRequestStatus]

        limit : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskListEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.list_my_tasks()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_my_tasks(status=status, limit=limit, request_options=request_options)
        return _response.data

    async def comment_on_task(
        self, *, task_id: str, body: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TaskCommentEnvelope:
        """
        Add a comment to a task. Supports @mentions in the mentions array.

        Parameters
        ----------
        task_id : str
            The task ID to comment on.

        body : str
            Comment body (markdown).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskCommentEnvelope
            Success

        Examples
        --------
        import asyncio

        from reload import AsyncReloadApi

        client = AsyncReloadApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.comment_on_task(
                task_id="taskId",
                body="body",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.comment_on_task(task_id=task_id, body=body, request_options=request_options)
        return _response.data
